### ISSUE TITLE
Add Great Basin National Park

### ISSUE THREAD

**Issue by katiejolly** [katiejolly/nationalparkcolors#3]
[Poster image](https://images-na.ssl-images-amazon.com/images/I/71-bxEorH3L._SY679_.jpg)

**Comment by MeganStodel** [comment]
I'd be happy to do this and #2 , if you're looking for contributors!

**Comment by katiejolly-ookla** [comment]
That would be great! I don't have a good workflow right now for people adding new palettes. Running the readme requires a specific font to be installed on your machine (and it seems like a bigger ask than it's worth for someone to do that). 

Maybe let's start with you looking through those posters and picking a good palette? You can then add the palette to the top of the R file (the palette list). I'll then run the readme myself with your palette added (and in the process come up with a better way for other people to contribute). 

If you're on chrome I like using the [ColorPick Eyedropper](https://chrome.google.com/webstore/detail/colorpick-eyedropper/ohcpnigalekghcmgcdcenkpelffpdolg?hl=en) for getting colors from images & websites!

**Comment by MeganStodel** [comment]
That sounds like a good idea - I'll have a look later today :)

**Comment by katiejolly-ookla** [comment]
No rush, I'm not going to get to any of the things on my part until tonight at the very earliest :)
